# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Feature workflow

on:
  push:
    branches:
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
    - 'release/**'

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and publish with Maven
      run: |
        # Versioning setup
        version_prefix=`mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout --file pom.xml | awk -F. '{print $1"."$2}'`
        version="$version_prefix.${{github.run_number}}-$GITHUB_SHA"
        echo "Setting artifact version to $version"
        # Push version to env
        echo "ARTIFACT_VERSION=$version" >> $GITHUB_ENV
        # Overwrite local artifact version
        mvn -B versions:set -DnewVersion="$version" --file pom.xml
        mvn -B deploy --file pom.xml
        cp "target/carshop-${version}.jar" "target/carshop.jar"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
